import type { GroupSpec } from "../types";

/** 通胀・货币 */
export const inflation: GroupSpec = {
  id: "inflation",
  title: "通胀・货币",
  charts: [
    {
      id: "copper-gold",
      title: "铜金比与 PPI",
      subtitle: "吨铜值多少盎司金:升=再通胀/risk-on,降=避险",
      series: [
        { csv: "macro/copper_gold_ppi", col: "copper_gold_ratio_daily", name: "铜金比(日,LME)" },
        { csv: "macro/copper_gold_ppi", col: "ppi_all_commod", name: "PPI 全商品 YoY", axis: 1, yoyMonths: 12 },
        { csv: "macro/copper_gold_ppi", col: "copper_gold_ratio", name: "铜金比(月,IMF)", off: true },
      ],
      y0: { name: "盎司金/吨铜" },
      y1: { name: "YoY", fmt: "pct" },
      note: "日频腿 = LME 现汇结算(T+1 滞后一日)÷ LBMA 现货金;纯 COMEX 因 2024 后关税溢价被弃用。",
      defaultYears: 10,
    },
    {
      id: "oil-gold",
      title: "油金比与 CPI",
      subtitle: "桶油值多少盎司金 —— 能源通胀温度计",
      series: [
        { csv: "macro/oil_gold_cpi", col: "oil_gold_ratio", name: "油金比" },
        { csv: "macro/oil_gold_cpi", col: "cpi_all_urban", name: "CPI YoY", axis: 1, yoyMonths: 12 },
        { csv: "macro/oil_gold_cpi", col: "wti_usd_bbl", name: "WTI($/桶)", axis: 1, off: true },
      ],
      y0: { name: "盎司金/桶" },
      y1: { name: "YoY", fmt: "pct" },
      defaultYears: 10,
    },
    {
      id: "inflation-expectations",
      title: "通胀与货币政策预期",
      subtitle: "盈亏平衡通胀 + 5y5y 远期 vs 联储目标利率",
      series: [
        { csv: "macro/inflation_monetary", col: "breakeven_5y", name: "5Y 盈亏平衡" },
        { csv: "macro/inflation_monetary", col: "fwd_5y5y_infl", name: "5y5y 远期通胀" },
        { csv: "macro/inflation_monetary", col: "breakeven_10y", name: "10Y 盈亏平衡", off: true },
        { csv: "macro/inflation_monetary", col: "fed_funds_target", name: "联储目标利率", axis: 1, step: true },
      ],
      y0: { name: "通胀预期", fmt: "pct" },
      y1: { name: "政策利率", fmt: "pct" },
      hLines: [{ value: 2, label: "2% 目标" }],
      defaultYears: 10,
    },
    {
      id: "us-cpi-ppi-mom",
      title: "美国 CPI / PPI 月环比",
      subtitle: "BLS 官方发布:季调指数本地计算 MoM",
      series: [
        { csv: "macro/us_inflation_releases", col: "cpi_headline_mom", name: "CPI MoM" },
        { csv: "macro/us_inflation_releases", col: "cpi_core_mom", name: "核心 CPI MoM" },
        { csv: "macro/us_inflation_releases", col: "ppi_headline_mom", name: "PPI MoM" },
        { csv: "macro/us_inflation_releases", col: "ppi_core_mom", name: "核心 PPI MoM" },
        { csv: "macro/us_inflation_releases", col: "ppi_core_ex_food_energy_trade_mom", name: "PPI 去食能贸易 MoM", off: true },
      ],
      y0: { name: "MoM", fmt: "pct" },
      hLines: [{ value: 0 }],
      defaultYears: 5,
    },
    {
      id: "us-cpi-ppi-yoy",
      title: "美国 CPI / PPI 同比",
      subtitle: "BLS 官方发布:季调指数本地计算 YoY",
      series: [
        { csv: "macro/us_inflation_releases", col: "cpi_headline_yoy", name: "CPI YoY" },
        { csv: "macro/us_inflation_releases", col: "cpi_core_yoy", name: "核心 CPI YoY" },
        { csv: "macro/us_inflation_releases", col: "ppi_headline_yoy", name: "PPI YoY" },
        { csv: "macro/us_inflation_releases", col: "ppi_core_yoy", name: "核心 PPI YoY" },
        { csv: "macro/us_inflation_releases", col: "ppi_core_ex_food_energy_trade_yoy", name: "PPI 去食能贸易 YoY", off: true },
      ],
      y0: { name: "YoY", fmt: "pct" },
      hLines: [{ value: 0 }, { value: 2, label: "2%" }],
      defaultYears: 5,
    },
    {
      id: "us-pce-inflation",
      title: "美国 PCE 通胀",
      subtitle: "BEA 官方 NIPA:美联储偏好的通胀指标",
      series: [
        { csv: "macro/us_inflation_releases", col: "pce_yoy", name: "PCE YoY" },
        { csv: "macro/us_inflation_releases", col: "core_pce_yoy", name: "核心 PCE YoY" },
        { csv: "macro/us_inflation_releases", col: "pce_mom", name: "PCE MoM", off: true },
        { csv: "macro/us_inflation_releases", col: "core_pce_mom", name: "核心 PCE MoM", off: true },
      ],
      y0: { name: "通胀率", fmt: "pct" },
      hLines: [{ value: 0 }, { value: 2, label: "2%" }],
      defaultYears: 5,
    },
  ],
};
